### ISSUE TITLE
WooCommerce templates needs to be updated

### ISSUE THREAD

**Issue by drbe4t** [themebeans/ava#1]
Hey I know you're guys aren't maintaining support. So I wanted to know how I could updated WooCommerce templates?

**Comment by richtabor** [comment]
Hey @drbe4t, totally missed this! You could paste the details of what needs to be specifically updated here and we'll take a look at it - or even better, if you'd like to get your feet wet in development, you could open up a PR with the proposed changes and I'll review and merge it if we're all good. 👍

**Comment by drbe4t** [comment]
I'll take a stab at it tomorrow and see if I can figure out how to get it done. :) I'll let you know next week if I can get figured out. haha Thanks for getting back to me.

**Comment by richtabor** [comment]
Resolved via #2
